In [55]:
import pandas as pd

In [57]:
bank_ds = pd.read_csv('loan.csv')

C:\Users\pabar\AppData\Local\Temp\ipykernel_10792\3558088723.py:1: DtypeWarning: Columns (19,47,55,112,123,124,125,128,129,130,133,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  bank_ds = pd.read_csv('loan.csv')

In [59]:
bank_ds.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
bank_ds.columns.tolist()

['id',
 'member_id',
 'loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'term',
 'int_rate',
 'installment',
 'grade',
 'sub_grade',
 'emp_title',
 'emp_length',
 'home_ownership',
 'annual_inc',
 'verification_status',
 'issue_d',
 'loan_status',
 'pymnt_plan',
 'url',
 'desc',
 'purpose',
 'title',
 'zip_code',
 'addr_state',
 'dti',
 'delinq_2yrs',
 'earliest_cr_line',
 'inq_last_6mths',
 'mths_since_last_delinq',
 'mths_since_last_record',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'revol_util',
 'total_acc',
 'initial_list_status',
 'out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'last_pymnt_d',
 'last_pymnt_amnt',
 'next_pymnt_d',
 'last_credit_pull_d',
 'collections_12_mths_ex_med',
 'mths_since_last_major_derog',
 'policy_code',
 'application_type',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'open_acc_6m',
 'open_act_il',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'total_bal_il',
 'il_util',
 'open_rv_12m',
 'open_rv_24m',
 'max_bal_bc',
 'all_util',
 'total_rev_hi_lim',
 'inq_fi',
 'total_cu_tl',
 'inq_last_12m',
 'acc_open_past_24mths',
 'avg_cur_bal',
 'bc_open_to_buy',
 'bc_util',
 'chargeoff_within_12_mths',
 'delinq_amnt',
 'mo_sin_old_il_acct',
 'mo_sin_old_rev_tl_op',
 'mo_sin_rcnt_rev_tl_op',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_bc',
 'mths_since_recent_bc_dlq',
 'mths_since_recent_inq',
 'mths_since_recent_revol_delinq',
 'num_accts_ever_120_pd',
 'num_actv_bc_tl',
 'num_actv_rev_tl',
 'num_bc_sats',
 'num_bc_tl',
 'num_il_tl',
 'num_op_rev_tl',
 'num_rev_accts',
 'num_rev_tl_bal_gt_0',
 'num_sats',
 'num_tl_120dpd_2m',
 'num_tl_30dpd',
 'num_tl_90g_dpd_24m',
 'num_tl_op_past_12m',
 'pct_tl_nvr_dlq',
 'percent_bc_gt_75',
 'pub_rec_bankruptcies',
 'tax_liens',
 'tot_hi_cred_lim',
 'total_bal_ex_mort',
 'total_bc_limit',
 'total_il_high_credit_limit',
 'revol_bal_joint',
 'sec_app_earliest_cr_line',
 'sec_app_inq_last_6mths',
 'sec_app_mort_acc',
 'sec_app_open_acc',
 'sec_app_revol_util',
 'sec_app_open_act_il',
 'sec_app_num_rev_accts',
 'sec_app_chargeoff_within_12_mths',
 'sec_app_collections_12_mths_ex_med',
 'sec_app_mths_since_last_major_derog',
 'hardship_flag',
 'hardship_type',
 'hardship_reason',
 'hardship_status',
 'deferral_term',
 'hardship_amount',
 'hardship_start_date',
 'hardship_end_date',
 'payment_plan_start_date',
 'hardship_length',
 'hardship_dpd',
 'hardship_loan_status',
 'orig_projected_additional_accrued_interest',
 'hardship_payoff_balance_amount',
 'hardship_last_payment_amount',
 'disbursement_method',
 'debt_settlement_flag',
 'debt_settlement_flag_date',
 'settlement_status',
 'settlement_date',
 'settlement_amount',
 'settlement_percentage',
 'settlement_term']

In [63]:
selected_cols = [
    "loan_amnt",
    "term",
    "int_rate",
    "installment",
    "grade",
    "sub_grade",
    "emp_length",
    "home_ownership",
    "annual_inc",
    "verification_status",
    "purpose",
    "dti",
    "delinq_2yrs",
    "inq_last_6mths",
    "open_acc",
    "pub_rec",
    "revol_util",
    "total_acc",
    "loan_status"
]

In [65]:
bank_ds = bank_ds[selected_cols]
bank_ds.head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_util,total_acc,loan_status
0,2500,36 months,13.56,84.92,C,C1,10+ years,RENT,55000.0,Not Verified,debt_consolidation,18.24,0.0,1.0,9.0,1.0,10.3,34.0,Current
1,30000,60 months,18.94,777.23,D,D2,10+ years,MORTGAGE,90000.0,Source Verified,debt_consolidation,26.52,0.0,0.0,13.0,1.0,24.2,44.0,Current
2,5000,36 months,17.97,180.69,D,D1,6 years,MORTGAGE,59280.0,Source Verified,debt_consolidation,10.51,0.0,0.0,8.0,0.0,19.1,13.0,Current
3,4000,36 months,18.94,146.51,D,D2,10+ years,MORTGAGE,92000.0,Source Verified,debt_consolidation,16.74,0.0,0.0,10.0,0.0,78.1,13.0,Current
4,30000,60 months,16.14,731.78,C,C4,10+ years,MORTGAGE,57250.0,Not Verified,debt_consolidation,26.35,0.0,0.0,12.0,0.0,3.6,26.0,Current

In [67]:
bank_ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260668 entries, 0 to 2260667
Data columns (total 19 columns):
 #   Column               Dtype
---  ------               -----
 0   loan_amnt            int64
 1   term                 object
 2   int_rate             float64
 3   installment          float64
 4   grade                object
 5   sub_grade            object
 6   emp_length           object
 7   home_ownership       object
 8   annual_inc           float64
 9   verification_status  object
 10  purpose              object
 11  dti                  float64
 12  delinq_2yrs          float64
 13  inq_last_6mths       float64
 14  open_acc             float64
 15  pub_rec              float64
 16  revol_util           float64
 17  total_acc            float64
 18  loan_status          object
dtypes: float64(10), int64(1), object(8)
memory usage: 327.7+ MB

In [69]:
bank_ds['loan_status'].value_counts()/len(bank_ds)*100  ##embalanced class, based on values in %

loan_status
Fully Paid                                             46.090448
Current                                                40.682444
Charged Off                                            11.574234
Late (31-120 days)                                      0.968608
In Grace Period                                         0.395989
Late (16-30 days)                                       0.165305
Does not meet the credit policy. Status:Fully Paid      0.087939
Does not meet the credit policy. Status:Charged Off     0.033663
Default                                                 0.001371
Name: count, dtype: float64

Considering completed loans to ensure a reliable target

In [71]:
bank_ds = bank_ds[bank_ds['loan_status'].isin(["Fully Paid","Charged Off"])]

In [73]:
len(bank_ds)

1303607

In [75]:

bank_ds['target'] = bank_ds['loan_status'].map({
    "Fully Paid": 0,
    "Charged Off":1
})

In [77]:
bank_ds['target'].value_counts(normalize=True)

target
0    0.799284
1    0.200716
Name: proportion, dtype: float64

In [80]:
(bank_ds.isnull().sum() / len(bank_ds) * 100).sort_values(ascending=False)

emp_length             5.788094
revol_util             0.062135
dti                    0.023934
inq_last_6mths         0.000077
loan_amnt              0.000000
loan_status            0.000000
total_acc              0.000000
pub_rec                0.000000
open_acc               0.000000
delinq_2yrs            0.000000
purpose                0.000000
term                   0.000000
verification_status    0.000000
annual_inc             0.000000
home_ownership         0.000000
sub_grade              0.000000
grade                  0.000000
installment            0.000000
int_rate               0.000000
target                 0.000000
dtype: float64

In [82]:
bank_ds['emp_length'].describe()

count       1228153
unique           11
top       10+ years
freq         428547
Name: emp_length, dtype: object

In [87]:
bank_ds['emp_length'].head()

100      5 years
152     < 1 year
170    10+ years
186    10+ years
215      3 years
Name: emp_length, dtype: object

In [91]:
bank_ds['emp_length'].value_counts()  ##variabile categorica ordinale

emp_length
10+ years    428547
2 years      117820
< 1 year     104550
3 years      104200
1 year        85677
5 years       81623
4 years       78029
6 years       60933
8 years       59125
7 years       58145
9 years       49504
Name: count, dtype: int64

In [95]:
def convert_emp_length(x):
    if pd.isnull(x):
        return None
    if x == "< 1 year":
        return 0
    if x == "10+ years":
        return 10
    return int(x.split()[0])

In [99]:
bank_ds["emp_length_num"] = bank_ds["emp_length"].apply(convert_emp_length)

In [109]:
bank_ds.isnull().sum()

loan_amnt                  0
term                       0
int_rate                   0
installment                0
grade                      0
sub_grade                  0
emp_length             75454
home_ownership             0
annual_inc                 0
verification_status        0
purpose                    0
dti                      312
delinq_2yrs                0
inq_last_6mths             1
open_acc                   0
pub_rec                    0
revol_util               810
total_acc                  0
loan_status                0
target                     0
emp_length_num             0
dtype: int64

In [105]:
bank_ds["emp_length_num"].fillna(-1, inplace=True)  ##I encoded missing values as -1 to represent an unknown category, preserving information without distorting the ordinal structure

C:\Users\pabar\AppData\Local\Temp\ipykernel_10792\4271132971.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bank_ds["emp_length_num"].fillna(-1, inplace=True)  ##I encoded missing values as -1 to represent an unknown category, preserving information without distorting the ordinal structure

In [111]:
bank_ds["emp_length_num"].isnull().sum()

0

In [113]:
bank_ds.drop("emp_length", axis=1, inplace=True)

In [117]:
bank_ds["emp_length_num"].value_counts()

emp_length_num
 10.0    428547
 2.0     117820
 0.0     104550
 3.0     104200
 1.0      85677
 5.0      81623
 4.0      78029
-1.0      75454
 6.0      60933
 8.0      59125
 7.0      58145
 9.0      49504
Name: count, dtype: int64

I inspected data types using df.info() and identified numeric fields stored as strings, such as percentages and durations, which required cleaning before modeling.

In [120]:
bank_ds["term"].value_counts()

term
36 months    988754
60 months    314853
Name: count, dtype: int64

In [134]:
bank_ds["term"].head()
bank_ds["term"].dtype
bank_ds["term"].value_counts()

term
36    988754
60    314853
Name: count, dtype: int64

In [122]:
bank_ds["int_rate"].value_counts()

int_rate
10.99    37282
11.99    31618
13.99    28730
5.32     26732
9.17     25932
         ...
17.44        1
14.28        1
13.19        1
11.16        1
17.46        1
Name: count, Length: 654, dtype: int64

In [124]:
bank_ds["revol_util"].value_counts()

revol_util
0.0      6691
57.0     2562
54.0     2560
58.0     2553
53.0     2544
         ...
116.2       1
125.0       1
120.9       1
125.2       1
154.9       1
Name: count, Length: 1363, dtype: int64

In [138]:
bank_ds.isnull().sum()

loan_amnt                0
term                     0
int_rate                 0
installment              0
grade                    0
sub_grade                0
home_ownership           0
annual_inc               0
verification_status      0
purpose                  0
dti                    312
delinq_2yrs              0
inq_last_6mths           1
open_acc                 0
pub_rec                  0
revol_util             810
total_acc                0
loan_status              0
target                   0
emp_length_num           0
dtype: int64

In [140]:
##gestione dei missing values

In [144]:
bank_ds["dti"] = bank_ds["dti"].fillna(bank_ds["dti"].median())
bank_ds["revol_util"] = bank_ds["revol_util"].fillna(bank_ds["revol_util"].median())
bank_ds["inq_last_6mths"] = bank_ds["inq_last_6mths"].fillna(0)

In [149]:
bank_ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1303607 entries, 100 to 2260664
Data columns (total 20 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   loan_amnt            1303607 non-null  int64
 1   term                 1303607 non-null  int32
 2   int_rate             1303607 non-null  float64
 3   installment          1303607 non-null  float64
 4   grade                1303607 non-null  object
 5   sub_grade            1303607 non-null  object
 6   home_ownership       1303607 non-null  object
 7   annual_inc           1303607 non-null  float64
 8   verification_status  1303607 non-null  object
 9   purpose              1303607 non-null  object
 10  dti                  1303607 non-null  float64
 11  delinq_2yrs          1303607 non-null  float64
 12  inq_last_6mths       1303607 non-null  float64
 13  open_acc             1303607 non-null  float64
 14  pub_rec              1303607 non-null  float64
 15  revol_util           1303607 non-null  float64
 16  total_acc            1303607 non-null  float64
 17  loan_status          1303607 non-null  object
 18  target               1303607 non-null  int64
 19  emp_length_num       1303607 non-null  float64
dtypes: float64(11), int32(1), int64(2), object(6)
memory usage: 203.9+ MB

In [151]:
bank_ds["purpose"].value_counts()

purpose
debt_consolidation    757591
credit_card           285704
home_improvement       84495
other                  74934
major_purchase         28328
medical                15023
small_business         15010
car                    14120
moving                  9172
vacation                8732
house                   6967
wedding                 2294
renewable_energy         911
educational              326
Name: count, dtype: int64

In [157]:
bank_ds["verification_status"].value_counts()

verification_status
Source Verified    503726
Verified           407676
Not Verified       392205
Name: count, dtype: int64

In [159]:
bank_ds["grade"].value_counts()

grade
B    380152
C    369928
A    226243
D    195280
E     91570
F     31483
G      8951
Name: count, dtype: int64

In [161]:
#OHE applied to 3 cols

In [163]:
categorical_cols = [
    "home_ownership",
    "verification_status",
    "purpose"
]

In [167]:
bank_ds.shape

(1303607, 20)

In [171]:
bank_ds = pd.get_dummies(bank_ds, columns=categorical_cols, drop_first=True)

In [173]:
bank_ds.shape

(1303607, 37)

In [ ]:
## feature ordinale (non OHE)

In [175]:
grade_map = {"A":1, "B":2, "C":3, "D":4, "E":5, "F":6, "G":7}
bank_ds["grade"] = bank_ds["grade"].map(grade_map)

In [177]:
bank_ds["grade"].value_counts()

grade
2    380152
3    369928
1    226243
4    195280
5     91570
6     31483
7      8951
Name: count, dtype: int64

In [ ]:
##elimino la fearure subgrade in quanto è piu dettagliata del grade ma ridondante

In [181]:
bank_ds.drop("sub_grade", axis=1, inplace=True)

In [183]:
bank_ds.shape

(1303607, 36)

In [187]:
bank_ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1303607 entries, 100 to 2260664
Data columns (total 36 columns):
 #   Column                               Non-Null Count    Dtype
---  ------                               --------------    -----
 0   loan_amnt                            1303607 non-null  int64
 1   term                                 1303607 non-null  int32
 2   int_rate                             1303607 non-null  float64
 3   installment                          1303607 non-null  float64
 4   grade                                1303607 non-null  int64
 5   annual_inc                           1303607 non-null  float64
 6   dti                                  1303607 non-null  float64
 7   delinq_2yrs                          1303607 non-null  float64
 8   inq_last_6mths                       1303607 non-null  float64
 9   open_acc                             1303607 non-null  float64
 10  pub_rec                              1303607 non-null  float64
 11  revol_util                           1303607 non-null  float64
 12  total_acc                            1303607 non-null  float64
 13  loan_status                          1303607 non-null  object
 14  target                               1303607 non-null  int64
 15  emp_length_num                       1303607 non-null  float64
 16  home_ownership_MORTGAGE              1303607 non-null  bool
 17  home_ownership_NONE                  1303607 non-null  bool
 18  home_ownership_OTHER                 1303607 non-null  bool
 19  home_ownership_OWN                   1303607 non-null  bool
 20  home_ownership_RENT                  1303607 non-null  bool
 21  verification_status_Source Verified  1303607 non-null  bool
 22  verification_status_Verified         1303607 non-null  bool
 23  purpose_credit_card                  1303607 non-null  bool
 24  purpose_debt_consolidation           1303607 non-null  bool
 25  purpose_educational                  1303607 non-null  bool
 26  purpose_home_improvement             1303607 non-null  bool
 27  purpose_house                        1303607 non-null  bool
 28  purpose_major_purchase               1303607 non-null  bool
 29  purpose_medical                      1303607 non-null  bool
 30  purpose_moving                       1303607 non-null  bool
 31  purpose_other                        1303607 non-null  bool
 32  purpose_renewable_energy             1303607 non-null  bool
 33  purpose_small_business               1303607 non-null  bool
 34  purpose_vacation                     1303607 non-null  bool
 35  purpose_wedding                      1303607 non-null  bool
dtypes: bool(20), float64(11), int32(1), int64(3), object(1)
memory usage: 189.0+ MB

In [189]:
bank_ds.isnull().sum().sum()

0

In [191]:
bank_ds.select_dtypes(include="object")

         loan_status
100       Fully Paid
152       Fully Paid
170       Fully Paid
186       Fully Paid
215       Fully Paid
...              ...
2260654  Charged Off
2260655  Charged Off
2260656   Fully Paid
2260658   Fully Paid
2260664   Fully Paid

[1303607 rows x 1 columns]

**EDA**